CREATE TABLE "apps" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"icon" jsonb,
	"is_hidden" boolean DEFAULT false,
	"channel" jsonb,
	"title" text,
	"description" text,
	"url" text,
	"organization_id" text NOT NULL,
	"business_unit_id" text,
	"user_id" text,
	"version" text,
	"workflow_id" text,
	"options" jsonb,
	"credentials" jsonb,
	"default_credentials" jsonb,
	"product_id" text,
	"user_progress" jsonb,
	"app_type" text,
	"is_active" boolean DEFAULT false,
	"is_deleted" boolean DEFAULT false,
	"categories" jsonb,
	"channels_or_platforms" jsonb,
	"banner_image" text,
	"icon_image" text,
	"sub_workflows" jsonb,
	"root_channel_workflow_id" text,
	"product_type" text,
	"product_code" text,
	"created_from" text,
	"direct_data_board" jsonb,
	"tags" jsonb,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"name" text NOT NULL,
	"description" text,
	"apply_to" text DEFAULT 'all',
	"app_id" text,
	"is_default" boolean DEFAULT false,
	"organization_id" text NOT NULL,
	"reference_id" text,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "emailsenders" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"title" text,
	"description" text,
	"email" text NOT NULL,
	"user_id" text,
	"organization_id" text,
	"deleted_at" timestamp,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "emailtemplates" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"name" text NOT NULL,
	"subject" text NOT NULL,
	"body" text NOT NULL,
	"variables" jsonb,
	"status" text,
	"category" text,
	"unsubscribe_link" text,
	"unsubscribe_text" text,
	"links" jsonb,
	"organization_id" text,
	"attachments" jsonb,
	"app_id" text,
	"board_id" text,
	"template_language" text,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "files" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"name" text NOT NULL,
	"organization_id" text,
	"short_path" text NOT NULL,
	"is_public" boolean DEFAULT false,
	"size" integer,
	"brief" text,
	"description" text,
	"file_type" text,
	"file_extension" text,
	"file_path" text,
	"file_url" text,
	"file_thumbnail_url" text,
	"ttl" integer DEFAULT 0,
	"will_delete_at" timestamp,
	"deleted" boolean DEFAULT false,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "forms" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"name" text NOT NULL,
	"description" text,
	"extended_from" text,
	"board_id" text,
	"board_name" text,
	"type" text,
	"engagement_count" integer DEFAULT 0,
	"submitted_count" integer DEFAULT 0,
	"teams" jsonb,
	"owner" jsonb,
	"organization_id" text NOT NULL,
	"start_date" text,
	"end_date" text,
	"app_id" text NOT NULL,
	"is_active" boolean DEFAULT true,
	"created_by" text,
	"use_captcha" boolean DEFAULT false,
	"hidden" boolean DEFAULT false,
	"data_board_id" text,
	"contact_board_id" text,
	"submit_button_text" text DEFAULT 'Submit',
	"footer" text DEFAULT 'Powered by iMBrace Limited',
	"header" text,
	"sub_header" text,
	"banner_image" text,
	"logo" text,
	"fields" jsonb,
	"map_to_contact" jsonb,
	"is_system" boolean DEFAULT false,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ideaproducts" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"title" text NOT NULL,
	"support_free_plan" boolean DEFAULT true,
	"root_workflow_id" text NOT NULL,
	"organization_id" text NOT NULL,
	"business_unit_id" text,
	"user_id" text,
	"version" text,
	"description" text,
	"use_cases" jsonb,
	"price" integer DEFAULT 0,
	"currency" text,
	"is_deleted" boolean DEFAULT false,
	"is_public" boolean DEFAULT false,
	"product_type" text,
	"template" jsonb,
	"banner_image" text,
	"why_use" text,
	"brief" text,
	"tags" jsonb,
	"categories" jsonb,
	"channels_or_platforms" jsonb,
	"default_credentials" jsonb,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ideas" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"title" text NOT NULL,
	"channel" jsonb,
	"credentials" jsonb,
	"user_progress" jsonb,
	"is_active" boolean DEFAULT false,
	"options" jsonb,
	"custom_data" jsonb,
	"organization_id" text NOT NULL,
	"business_unit_id" text,
	"user_id" text,
	"version" text,
	"description" text,
	"icon" jsonb,
	"idea_type" text,
	"url" text,
	"faq" text,
	"channels_or_platforms" jsonb,
	"categories" jsonb,
	"workflow_id" text NOT NULL,
	"price" integer DEFAULT 0,
	"support_free_plan" boolean DEFAULT true,
	"tags" jsonb,
	"product_id" text,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"title" text NOT NULL,
	"organization_id" text NOT NULL,
	"app_id" text NOT NULL,
	"business_unit_id" text,
	"user_id" text,
	"version" text,
	"description" text,
	"use_cases" jsonb,
	"price" text,
	"currency" text,
	"is_deleted" boolean DEFAULT false,
	"is_public" boolean DEFAULT false,
	"template" jsonb,
	"banner_image" text,
	"why_use" text,
	"brief" text,
	"categories" jsonb,
	"tags" jsonb,
	"channels_or_platforms" jsonb,
	"default_credentials" jsonb,
	"max_instances" integer DEFAULT 0,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "templates" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"graph" jsonb NOT NULL,
	"description" text,
	"original_id" text,
	"organization_id" text NOT NULL,
	"deps" jsonb,
	"active" boolean DEFAULT false,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "usecases" (
	"id" text PRIMARY KEY NOT NULL,
	"doc_name" text,
	"public_id" text,
	"title" text NOT NULL,
	"version" integer DEFAULT 1,
	"organization_id" text NOT NULL,
	"short_description" text,
	"description" text,
	"type" text DEFAULT 'default',
	"channel_id" text,
	"features" jsonb,
	"thumbnail_url" text,
	"hover_thumbnail_url" text,
	"tags" jsonb,
	"video_url" text,
	"demo_url" text,
	"demo_image_url" text,
	"how_it_works" jsonb,
	"suggestion_prompts" jsonb,
	"supported_channels" jsonb,
	"integrations" jsonb,
	"template_id" text,
	"assistant_id" text,
	"user_id" text,
	"is_deleted" boolean DEFAULT false,
	"agent_type" text,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
