CREATE TABLE "builtin_agents" (
	"id" text PRIMARY KEY NOT NULL,
	"assistant_id" text NOT NULL,
	"is_builtin" boolean DEFAULT true,
	"title" text,
	"name" text,
	"short_description" text,
	"description" text,
	"agent_type" text,
	"suggestion_prompts" jsonb DEFAULT '[]'::jsonb,
	"thumbnail_url" text,
	"hover_thumbnail_url" text,
	"instructions" text,
	"core_task" text,
	"personality_role" text,
	"tone_and_style" text,
	"response_length" text,
	"banned_words" text,
	"model" text,
	"model_id" text,
	"temperature" real,
	"streaming" boolean,
	"show_thinking_process" boolean,
	"use_memory" boolean,
	"vibe_code" boolean,
	"mode" text,
	"provider_id" text,
	"workflow_name" text,
	"credential_id" text,
	"credential_name" text,
	"board_ids" jsonb DEFAULT '[]'::jsonb,
	"folder_ids" jsonb DEFAULT '[]'::jsonb,
	"default_folder_id" text,
	"file_ids" jsonb DEFAULT '[]'::jsonb,
	"knowledge_hubs" jsonb DEFAULT '[]'::jsonb,
	"workflow_function_call" jsonb DEFAULT '[]'::jsonb,
	"sub_agents" jsonb DEFAULT '[]'::jsonb,
	"preload_information" text,
	"preload_information_type" text,
	"guardrail_id" text,
	"document_ai" jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb,
	"version" integer DEFAULT 1,
	"updated_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "builtin_agents_assistant_id_unique" UNIQUE("assistant_id")
);
