import { pgTable, text, integer, boolean, jsonb, timestamp, varchar, real } from 'drizzle-orm/pg-core'
import { mysqlTable, text as mysqlText, varchar as mysqlVarchar, int, boolean as mysqlBoolean, json, timestamp as mysqlTimestamp } from 'drizzle-orm/mysql-core'

// ================= PostgreSQL Tables =================

export const pgApps = pgTable('apps', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    icon: jsonb('icon'),
    is_hidden: boolean('is_hidden').default(false),
    channel: jsonb('channel'),
    title: text('title'),
    description: text('description'),
    url: text('url'),
    organization_id: text('organization_id').notNull(),
    business_unit_id: text('business_unit_id'),
    user_id: text('user_id'),
    version: text('version'),
    workflow_id: text('workflow_id'),
    options: jsonb('options'),
    credentials: jsonb('credentials'),
    default_credentials: jsonb('default_credentials'),
    product_id: text('product_id'),
    user_progress: jsonb('user_progress'),
    app_type: text('app_type'),
    is_active: boolean('is_active').default(false),
    is_deleted: boolean('is_deleted').default(false),
    categories: jsonb('categories'),
    channels_or_platforms: jsonb('channels_or_platforms'),
    banner_image: text('banner_image'),
    icon_image: text('icon_image'),
    sub_workflows: jsonb('sub_workflows'),
    root_channel_workflow_id: text('root_channel_workflow_id'),
    product_type: text('product_type'),
    product_code: text('product_code'),
    created_from: text('created_from'),
    direct_data_board: jsonb('direct_data_board'),
    tags: jsonb('tags'),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgEmailSenders = pgTable('emailsenders', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    title: text('title'),
    description: text('description'),
    email: text('email').notNull(),
    user_id: text('user_id'),
    organization_id: text('organization_id'),
    deleted_at: timestamp('deleted_at'),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgEmailTemplates = pgTable('emailtemplates', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    name: text('name').notNull(),
    subject: text('subject').notNull(),
    body: text('body').notNull(),
    variables: jsonb('variables'),
    status: text('status'),
    category: text('category'),
    unsubscribe_link: text('unsubscribe_link'),
    unsubscribe_text: text('unsubscribe_text'),
    links: jsonb('links'),
    organization_id: text('organization_id'),
    attachments: jsonb('attachments'),
    app_id: text('app_id'),
    board_id: text('board_id'),
    template_language: text('template_language'),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgFiles = pgTable('files', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    name: text('name').notNull(),
    organization_id: text('organization_id'),
    short_path: text('short_path').notNull(),
    is_public: boolean('is_public').default(false),
    size: integer('size'),
    brief: text('brief'),
    description: text('description'),
    file_type: text('file_type'),
    file_extension: text('file_extension'),
    file_path: text('file_path'),
    file_url: text('file_url'),
    file_thumbnail_url: text('file_thumbnail_url'),
    ttl: integer('ttl').default(0),
    will_delete_at: timestamp('will_delete_at'),
    deleted: boolean('deleted').default(false),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgForms = pgTable('forms', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    name: text('name').notNull(),
    description: text('description'),
    extended_from: text('extended_from'),
    board_id: text('board_id'),
    board_name: text('board_name'),
    type: text('type'),
    engagement_count: integer('engagement_count').default(0),
    submitted_count: integer('submitted_count').default(0),
    teams: jsonb('teams'),
    owner: jsonb('owner'),
    organization_id: text('organization_id').notNull(),
    start_date: text('start_date'),
    end_date: text('end_date'),
    app_id: text('app_id').notNull(),
    is_active: boolean('is_active').default(true),
    created_by: text('created_by'),
    use_captcha: boolean('use_captcha').default(false),
    hidden: boolean('hidden').default(false),
    data_board_id: text('data_board_id'),
    contact_board_id: text('contact_board_id'),
    submit_button_text: text('submit_button_text').default('Submit'),
    footer: text('footer').default('Powered by iMBrace Limited'),
    header: text('header'),
    sub_header: text('sub_header'),
    banner_image: text('banner_image'),
    logo: text('logo'),
    fields: jsonb('fields'),
    map_to_contact: jsonb('map_to_contact'),
    is_system: boolean('is_system').default(false),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgTemplates = pgTable('templates', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    name: text('name').notNull(),
    type: text('type').notNull(),
    graph: jsonb('graph').notNull(),
    description: text('description'),
    original_id: text('original_id'),
    organization_id: text('organization_id').notNull(),
    deps: jsonb('deps'),
    active: boolean('active').default(false),
    zip_s3_key: text('zip_s3_key'),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgMarketplaceTemplates = pgTable('marketplace_templates', {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description'),
    type: text('type').notNull(),
    organization_id: text('organization_id').notNull(),
    public_id: text('public_id'),
    active: boolean('active').default(true),
    metadata: jsonb('metadata').notNull(),
    zip_s3_key: text('zip_s3_key').notNull(),
    created_at: timestamp('created_at').defaultNow(),
    updated_at: timestamp('updated_at').defaultNow(),
})

export const pgUseCases = pgTable('usecases', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    title: text('title').notNull(),
    version: integer('version').default(1),
    organization_id: text('organization_id').notNull(),
    short_description: text('short_description'),
    description: text('description'),
    type: text('type').default('default'),
    channel_id: text('channel_id'),
    features: jsonb('features'),
    thumbnail_url: text('thumbnail_url'),
    hover_thumbnail_url: text('hover_thumbnail_url'),
    media: jsonb('media'),
    tags: jsonb('tags'),
    video_url: text('video_url'),
    demo_url: text('demo_url'),
    demo_image_url: text('demo_image_url'),
    how_it_works: jsonb('how_it_works'),
    suggestion_prompts: jsonb('suggestion_prompts'),
    supported_channels: jsonb('supported_channels'),
    integrations: jsonb('integrations'),
    template_id: text('template_id'),
    assistant_id: text('assistant_id'),
    user_id: text('user_id'),
    is_deleted: boolean('is_deleted').default(false),
    agent_type: text('agent_type'),
    // True when this use case is a team's auto-provisioned default agent.
    is_team_default_agent: boolean('is_team_default_agent').default(false),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

// Backfilled to match the 0000 migration shipped to dev RDS. Without these,
// `drizzle-kit generate` would produce a destructive 0001 that DROPs them.
export const pgCategories = pgTable('categories', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    name: text('name').notNull(),
    description: text('description'),
    apply_to: text('apply_to').default('all'),
    app_id: text('app_id'),
    is_default: boolean('is_default').default(false),
    organization_id: text('organization_id').notNull(),
    reference_id: text('reference_id'),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgIdeaProducts = pgTable('ideaproducts', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    title: text('title').notNull(),
    support_free_plan: boolean('support_free_plan').default(true),
    root_workflow_id: text('root_workflow_id').notNull(),
    organization_id: text('organization_id').notNull(),
    business_unit_id: text('business_unit_id'),
    user_id: text('user_id'),
    version: text('version'),
    description: text('description'),
    use_cases: jsonb('use_cases'),
    price: integer('price').default(0),
    currency: text('currency'),
    is_deleted: boolean('is_deleted').default(false),
    is_public: boolean('is_public').default(false),
    product_type: text('product_type'),
    template: jsonb('template'),
    banner_image: text('banner_image'),
    why_use: text('why_use'),
    brief: text('brief'),
    tags: jsonb('tags'),
    categories: jsonb('categories'),
    channels_or_platforms: jsonb('channels_or_platforms'),
    default_credentials: jsonb('default_credentials'),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgIdeas = pgTable('ideas', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    title: text('title').notNull(),
    channel: jsonb('channel'),
    credentials: jsonb('credentials'),
    user_progress: jsonb('user_progress'),
    is_active: boolean('is_active').default(false),
    options: jsonb('options'),
    custom_data: jsonb('custom_data'),
    organization_id: text('organization_id').notNull(),
    business_unit_id: text('business_unit_id'),
    user_id: text('user_id'),
    version: text('version'),
    description: text('description'),
    icon: jsonb('icon'),
    idea_type: text('idea_type'),
    url: text('url'),
    faq: text('faq'),
    channels_or_platforms: jsonb('channels_or_platforms'),
    categories: jsonb('categories'),
    workflow_id: text('workflow_id').notNull(),
    price: integer('price').default(0),
    support_free_plan: boolean('support_free_plan').default(true),
    tags: jsonb('tags'),
    product_id: text('product_id'),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgProducts = pgTable('products', {
    id: text('id').primaryKey(),
    doc_name: text('doc_name'),
    public_id: text('public_id'),
    title: text('title').notNull(),
    organization_id: text('organization_id').notNull(),
    app_id: text('app_id').notNull(),
    business_unit_id: text('business_unit_id'),
    user_id: text('user_id'),
    version: text('version'),
    description: text('description'),
    use_cases: jsonb('use_cases'),
    price: text('price'),
    currency: text('currency'),
    is_deleted: boolean('is_deleted').default(false),
    is_public: boolean('is_public').default(false),
    template: jsonb('template'),
    banner_image: text('banner_image'),
    why_use: text('why_use'),
    brief: text('brief'),
    categories: jsonb('categories'),
    tags: jsonb('tags'),
    channels_or_platforms: jsonb('channels_or_platforms'),
    default_credentials: jsonb('default_credentials'),
    max_instances: integer('max_instances').default(0),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

export const pgBuiltinAgents = pgTable('builtin_agents', {
    id: text('id').primaryKey(),
    assistant_id: text('assistant_id').notNull().unique(),
    is_builtin: boolean('is_builtin').default(true),

    title: text('title'),
    name: text('name'),
    short_description: text('short_description'),
    description: text('description'),
    agent_type: text('agent_type'),
    suggestion_prompts: jsonb('suggestion_prompts').default([]),
    thumbnail_url: text('thumbnail_url'),
    hover_thumbnail_url: text('hover_thumbnail_url'),

    instructions: text('instructions'),
    core_task: text('core_task'),
    personality_role: text('personality_role'),
    tone_and_style: text('tone_and_style'),
    response_length: text('response_length'),
    banned_words: text('banned_words'),
    model: text('model'),
    model_id: text('model_id'),
    temperature: real('temperature'),
    streaming: boolean('streaming'),
    show_thinking_process: boolean('show_thinking_process'),
    use_memory: boolean('use_memory'),
    vibe_code: boolean('vibe_code'),
    mode: text('mode'),
    provider_id: text('provider_id'),
    workflow_name: text('workflow_name'),
    credential_id: text('credential_id'),
    credential_name: text('credential_name'),
    board_ids: jsonb('board_ids').default([]),
    folder_ids: jsonb('folder_ids').default([]),
    default_folder_id: text('default_folder_id'),
    file_ids: jsonb('file_ids').default([]),
    knowledge_hubs: jsonb('knowledge_hubs').default([]),
    workflow_function_call: jsonb('workflow_function_call').default([]),
    sub_agents: jsonb('sub_agents').default([]),
    preload_information: text('preload_information'),
    preload_information_type: text('preload_information_type'),
    guardrail_id: text('guardrail_id'),
    document_ai: jsonb('document_ai'),
    metadata: jsonb('metadata').default({}),

    version: integer('version').default(1),
    updated_at: timestamp('updated_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow()
})

// ================= MySQL Tables =================

export const mysqlApps = mysqlTable('apps', {
    id: mysqlVarchar('id', { length: 255 }).primaryKey(),
    doc_name: mysqlText('doc_name'),
    public_id: mysqlVarchar('public_id', { length: 255 }),
    icon: json('icon'),
    is_hidden: mysqlBoolean('is_hidden').default(false),
    channel: json('channel'),
    title: mysqlText('title'),
    description: mysqlText('description'),
    url: mysqlText('url'),
    organization_id: mysqlVarchar('organization_id', { length: 255 }).notNull(),
    business_unit_id: mysqlVarchar('business_unit_id', { length: 255 }),
    user_id: mysqlVarchar('user_id', { length: 255 }),
    version: mysqlVarchar('version', { length: 50 }),
    workflow_id: mysqlVarchar('workflow_id', { length: 255 }),
    options: json('options'),
    credentials: json('credentials'),
    default_credentials: json('default_credentials'),
    product_id: mysqlVarchar('product_id', { length: 255 }),
    user_progress: json('user_progress'),
    app_type: mysqlVarchar('app_type', { length: 50 }),
    is_active: mysqlBoolean('is_active').default(false),
    is_deleted: mysqlBoolean('is_deleted').default(false),
    categories: json('categories'),
    channels_or_platforms: json('channels_or_platforms'),
    banner_image: mysqlText('banner_image'),
    icon_image: mysqlText('icon_image'),
    sub_workflows: json('sub_workflows'),
    root_channel_workflow_id: mysqlVarchar('root_channel_workflow_id', { length: 255 }),
    product_type: mysqlVarchar('product_type', { length: 100 }),
    product_code: mysqlVarchar('product_code', { length: 255 }),
    created_from: mysqlVarchar('created_from', { length: 255 }),
    direct_data_board: json('direct_data_board'),
    tags: json('tags'),
    updated_at: mysqlTimestamp('updated_at').defaultNow(),
    created_at: mysqlTimestamp('created_at').defaultNow()
})

export const mysqlEmailSenders = mysqlTable('emailsenders', {
    id: mysqlVarchar('id', { length: 255 }).primaryKey(),
    doc_name: mysqlVarchar('doc_name', { length: 50 }),
    public_id: mysqlVarchar('public_id', { length: 255 }),
    title: mysqlText('title'),
    description: mysqlText('description'),
    email: mysqlVarchar('email', { length: 255 }).notNull(),
    user_id: mysqlVarchar('user_id', { length: 255 }),
    organization_id: mysqlVarchar('organization_id', { length: 255 }),
    deleted_at: mysqlTimestamp('deleted_at'),
    updated_at: mysqlTimestamp('updated_at').defaultNow(),
    created_at: mysqlTimestamp('created_at').defaultNow()
})

export const mysqlEmailTemplates = mysqlTable('emailtemplates', {
    id: mysqlVarchar('id', { length: 255 }).primaryKey(),
    doc_name: mysqlVarchar('doc_name', { length: 50 }),
    public_id: mysqlVarchar('public_id', { length: 255 }),
    name: mysqlText('name').notNull(),
    subject: mysqlText('subject').notNull(),
    body: mysqlText('body').notNull(),
    variables: json('variables'),
    status: mysqlVarchar('status', { length: 50 }),
    category: mysqlVarchar('category', { length: 255 }),
    unsubscribe_link: mysqlText('unsubscribe_link'),
    unsubscribe_text: mysqlText('unsubscribe_text'),
    links: json('links'),
    organization_id: mysqlVarchar('organization_id', { length: 255 }),
    attachments: json('attachments'),
    app_id: mysqlVarchar('app_id', { length: 255 }),
    board_id: mysqlVarchar('board_id', { length: 255 }),
    template_language: mysqlVarchar('template_language', { length: 50 }),
    updated_at: mysqlTimestamp('updated_at').defaultNow(),
    created_at: mysqlTimestamp('created_at').defaultNow()
})

export const mysqlFiles = mysqlTable('files', {
    id: mysqlVarchar('id', { length: 255 }).primaryKey(),
    doc_name: mysqlVarchar('doc_name', { length: 50 }),
    public_id: mysqlVarchar('public_id', { length: 255 }),
    name: mysqlText('name').notNull(),
    organization_id: mysqlVarchar('organization_id', { length: 255 }),
    short_path: mysqlVarchar('short_path', { length: 255 }).notNull(),
    is_public: mysqlBoolean('is_public').default(false),
    size: int('size'),
    brief: mysqlText('brief'),
    description: mysqlText('description'),
    file_type: mysqlVarchar('file_type', { length: 100 }),
    file_extension: mysqlVarchar('file_extension', { length: 50 }),
    file_path: mysqlText('file_path'),
    file_url: mysqlText('file_url'),
    file_thumbnail_url: mysqlText('file_thumbnail_url'),
    ttl: int('ttl').default(0),
    will_delete_at: mysqlTimestamp('will_delete_at'),
    deleted: mysqlBoolean('deleted').default(false),
    updated_at: mysqlTimestamp('updated_at').defaultNow(),
    created_at: mysqlTimestamp('created_at').defaultNow()
})

export const mysqlForms = mysqlTable('forms', {
    id: mysqlVarchar('id', { length: 255 }).primaryKey(),
    doc_name: mysqlVarchar('doc_name', { length: 50 }),
    public_id: mysqlVarchar('public_id', { length: 255 }),
    name: mysqlText('name').notNull(),
    description: mysqlText('description'),
    extended_from: mysqlVarchar('extended_from', { length: 255 }),
    board_id: mysqlVarchar('board_id', { length: 255 }),
    board_name: mysqlText('board_name'),
    type: mysqlVarchar('type', { length: 50 }),
    engagement_count: int('engagement_count').default(0),
    submitted_count: int('submitted_count').default(0),
    teams: json('teams'),
    owner: json('owner'),
    organization_id: mysqlVarchar('organization_id', { length: 255 }).notNull(),
    start_date: mysqlVarchar('start_date', { length: 50 }),
    end_date: mysqlVarchar('end_date', { length: 50 }),
    app_id: mysqlVarchar('app_id', { length: 255 }).notNull(),
    is_active: mysqlBoolean('is_active').default(true),
    created_by: mysqlVarchar('created_by', { length: 255 }),
    use_captcha: mysqlBoolean('use_captcha').default(false),
    hidden: mysqlBoolean('hidden').default(false),
    data_board_id: mysqlVarchar('data_board_id', { length: 255 }),
    contact_board_id: mysqlVarchar('contact_board_id', { length: 255 }),
    submit_button_text: mysqlVarchar('submit_button_text', { length: 100 }).default('Submit'),
    footer: mysqlText('footer'),
    header: mysqlText('header'),
    sub_header: mysqlText('sub_header'),
    banner_image: mysqlText('banner_image'),
    logo: mysqlText('logo'),
    fields: json('fields'),
    map_to_contact: json('map_to_contact'),
    is_system: mysqlBoolean('is_system').default(false),
    updated_at: mysqlTimestamp('updated_at').defaultNow(),
    created_at: mysqlTimestamp('created_at').defaultNow()
})

export const mysqlTemplates = mysqlTable('templates', {
    id: mysqlVarchar('id', { length: 255 }).primaryKey(),
    doc_name: mysqlVarchar('doc_name', { length: 50 }),
    public_id: mysqlVarchar('public_id', { length: 255 }),
    name: mysqlText('name').notNull(),
    type: mysqlVarchar('type', { length: 100 }).notNull(),
    graph: json('graph').notNull(),
    description: mysqlText('description'),
    original_id: mysqlVarchar('original_id', { length: 255 }),
    organization_id: mysqlVarchar('organization_id', { length: 255 }).notNull(),
    deps: json('deps'),
    active: mysqlBoolean('active').default(false),
    updated_at: mysqlTimestamp('updated_at').defaultNow(),
    created_at: mysqlTimestamp('created_at').defaultNow()
})

export const mysqlUseCases = mysqlTable('usecases', {
    id: mysqlVarchar('id', { length: 255 }).primaryKey(),
    doc_name: mysqlVarchar('doc_name', { length: 50 }),
    public_id: mysqlVarchar('public_id', { length: 255 }),
    title: mysqlText('title').notNull(),
    version: int('version').default(1),
    organization_id: mysqlVarchar('organization_id', { length: 255 }).notNull(),
    short_description: mysqlText('short_description'),
    description: mysqlText('description'),
    type: mysqlVarchar('type', { length: 50 }).default('default'),
    channel_id: mysqlVarchar('channel_id', { length: 255 }),
    features: json('features'),
    thumbnail_url: mysqlText('thumbnail_url'),
    hover_thumbnail_url: mysqlText('hover_thumbnail_url'),
    media: json('media'),
    tags: json('tags'),
    video_url: mysqlText('video_url'),
    demo_url: mysqlText('demo_url'),
    demo_image_url: mysqlText('demo_image_url'),
    how_it_works: json('how_it_works'),
    suggestion_prompts: json('suggestion_prompts'),
    supported_channels: json('supported_channels'),
    integrations: json('integrations'),
    template_id: mysqlVarchar('template_id', { length: 255 }),
    assistant_id: mysqlVarchar('assistant_id', { length: 255 }),
    user_id: mysqlVarchar('user_id', { length: 255 }),
    is_deleted: mysqlBoolean('is_deleted').default(false),
    agent_type: mysqlVarchar('agent_type', { length: 100 }),
    // True when this use case is a team's auto-provisioned default agent.
    is_team_default_agent: mysqlBoolean('is_team_default_agent').default(false),
    updated_at: mysqlTimestamp('updated_at').defaultNow(),
    created_at: mysqlTimestamp('created_at').defaultNow()
})
