import { FieldType, Form, Field } from '../domains/interface/form';

const defaultLeadFields: Field[] = [
  {
    name: 'Full Name',
    description: 'The full name of the person',
    type: FieldType.ShortText,
    is_unique_identifier: false,
    is_default: true,
    hidden: false,
    is_identifier: true,
    data: [],
    default_value: '',
    required: true,
    placeholder: 'John Doe',
    field_name: 'name',
    title: 'Full Name',
    field_description:
      "This is the default required field. Can't be hidden or deleted.",
  },
  {
    name: 'Position',
    description: '',
    type: FieldType.ShortText,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [],
    default_value: '',
    required: false,
    placeholder: 'Head of Marketing',
    field_name: 'position',
    title: 'Position',
    field_description: '',
  },
  {
    name: 'Company',
    description: 'The name of the company',
    type: FieldType.ShortText,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [],
    default_value: '',
    required: false,
    placeholder: 'iMBrace Limited',
    field_name: 'company',
    title: 'Company',
    field_description: '',
  },
  {
    name: 'Phone',
    description: '55555555555',
    type: FieldType.ShortText,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [],
    default_value: '',
    required: false,
    placeholder: 'Enter your phone number',
    field_name: 'phone',
    title: 'Phone',
    field_description: '',
  },
  {
    name: 'Email',
    description: 'Email address',
    type: FieldType.Email,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [],
    default_value: '',
    required: false,
    placeholder: 'john.doe@imbrace.co',
    field_name: 'email',
    title: 'Email',
    field_description: '',
  },
  {
    name: 'Location',
    description: 'Country of residence',
    type: FieldType.SingleSelection,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [],
    default_value: 'USA',
    required: false,
    placeholder: 'Select your country',
    field_name: 'location',
    title: 'Country',
    field_description: '',
  },
  // Address
  {
    name: 'Address',
    description: 'The address of the person',
    type: FieldType.ShortText,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [],
    default_value: '',
    required: false,
    placeholder: 'Enter your address',
    field_name: 'address',
    title: 'Address',
    field_description: '',
  },
  // Interest Product
  {
    name: 'Interest Product',
    description: 'The product of interest',
    type: FieldType.MultiSelection,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [
      { value: 'Product A', _id: 'ProductA' },
      { value: 'Product B', _id: 'ProductB' }

    ],
    default_value: '',
    required: false,
    placeholder: 'Select your interest product',
    field_name: 'interest_product',
    title: 'Interest Product',
    field_description: '',
  },
  // Categories
  {
    name: 'Categories',
    description: 'The category of the person',
    type: FieldType.MultiSelection,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [
      { value: 'Marketing', _id: 'Marketing' },
      { value: 'Sales', _id: 'Sales' },
      { value: 'Product', _id: 'Product' },
    ],
    default_value: '',
    required: false,
    placeholder: 'Select your categories',
    field_name: 'categories',
    title: 'Categories',
    field_description: '',
  },
  // Remark
  {
    name: 'Remark',
    description: 'Any additional information',
    type: FieldType.LongText,
    is_unique_identifier: false,
    is_default: false,
    hidden: false,
    is_identifier: false,
    data: [],
    default_value: '',
    required: false,
    placeholder: 'Enter any additional information',
    field_name: 'remark',
    title: 'Remark',
    field_description: '',
  },
];

// Name
export const FormName: Field = {
  name: 'Name',
  description: 'The full name of the person',
  type: FieldType.ShortText,
  is_unique_identifier: false,
  is_default: true,
  hidden: false,
  is_identifier: true,
  data: [],
  default_value: '',
  required: true,
  placeholder: 'John Doe',
  field_name: 'name',
  title: 'Full Name',
  field_description:
    "This is the default required field. Can't be hidden or deleted.",
};

// Submission Source
export const SubmissionSource: Field = {
  name: 'Submission Source',
  description: '(System Generated) Which form this record came from',
  type: FieldType.ShortText,
  is_unique_identifier: false,
  hidden_in_form: true,
  is_default: true,
  hidden: false,
  is_identifier: false,
  data: [],
  default_value: 'Web',
  required: false,
  is_system: true,
  placeholder: 'Select the submission source',
  field_name: 'submission_source',
  title: 'Submission Source',
  field_description:
    "This is the default required field. Can't be hidden or deleted.",
};

// Submission Time
export const SubmissionTime: Field = {
  name: 'Submission Time',
  description: '(System Generated) When the form was submitted',
  type: FieldType.DateTime,
  is_unique_identifier: false,
  hidden_in_form: true,
  is_system: true,
  is_default: true,
  hidden: false,
  is_identifier: false,
  data: [],
  default_value: '',
  required: false,
  placeholder: 'Select the submission time',
  field_name: 'submission_time',
  title: 'Submission Time',
  field_description:
    "This is the default required field. Can't be hidden or deleted.",
};

export const FormOwner: Field = {
  name: 'Form Owner',
  description: '(System Generated) Default is the Form Owner specified in the associated form settings',
  type: FieldType.Assignee,
  is_unique_identifier: false,
  hidden_in_form: true,
  is_default: false,
  is_system: true,
  hidden: false,
  is_identifier: false,
  data: [],
  default_value: '',
  required: false,
  placeholder: 'Select the owner of the form',
  field_name: 'owner',
  title: 'Form Owner',
  field_description: '',
};

export const UTM: Field = {
  name: 'UTM',
  description: '(System Generated) The source of the submission and relationships between submissions',
  type: FieldType.ShortText,
  is_unique_identifier: false,
  hidden_in_form: true,
  is_default: false,
  hidden: false,
  is_identifier: false,
  data: [],
  default_value: '',
  required: false,
  placeholder: 'Enter the UTM parameters',
  field_name: 'utm',
  title: 'UTM',
  field_description: '',
};

export type DefaultFormConfig = {
  name?: string;
  description?: string;
  app_id?: string;
  organization_id?: string;
};

export const templateForm = (): Partial<Form> => {
  return {
    name: '',
    description:
      'Add any instructions here. Modify the fields below to customize your form. You can hide the default fields if not needed.',
    submit_button_text: 'Submit',
    footer: 'Powered by iMBrace Limited',
    header: 'Event Lead Management',
    sub_header: 'Add any instructions here. Modify the fields below to customize your form. You can hide the default fields if not needed.',
    fields: defaultLeadFields,
  };
};
